server {
    listen 80;
    listen [::]:80;
    server_name _;

    location /.well-known/acme-challenge {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_url;
    }
}

server {
    listen 443 ssl;
    server_name test-nginx-app.ru;

    ssl_сertificate /etc/letsencrypt/live/test-nginx-app.ru/fullchain.pem;
    ssl_сertificate_key /etc/letsencrypt/live/test-nginx-app.ru/privkey.pem;

    location / {
        root /static;
        index index.html;
    }
}